name: Hello World Action
author: Nivas
description: A simple hello world action that prints a message to the console.
branding:
  icon: "clock"
  color: "blue"
inputs: 
  who-to-greet:
    description: "Who to greet?"
    required: true
    default: "World"
outputs:
  time:
    description: "The time of the greeting"

runs:
  using: "docker"
  # image: 'docker://alpine:3.18'
  image: "Dockerfile

  args:
    - who-to-greet=${{ inputs.who-to-greet }}
  env:
    HELLO: "WORLD"